### ISSUE TITLE
You passed invalid parameters to 'firebase_app_distribution'.

### ISSUE THREAD

**Issue by lawicko** [fastlane-community/fastlane-plugin-firebase_app_distribution#4]
So I have installed the `firebase` binary, I logged in and have access to my projects. I installed the plugin and the relevant part of my `Fastfile` looks like this:
```
firebasePath = sh("which firebase")
firebaseDirectory = sh("dirname #{firebasePath}")
firebase_app_distribution(
        app: "1:642144225493:ios:1585402b689cc482",
        firebase_cli_path: "#{firebaseDirectory}")
```

The `which firebase` command resolves to `/usr/local/bin/firebase` so I can see the following errors when trying to execute this step:
```
[08:54:43]: Error setting value '/usr/local/bin/firebase
' for option 'firebase_cli_path'
[08:54:43]: You passed invalid parameters to 'firebase_app_distribution'.
[08:54:43]: Check out the error below and available options by running `fastlane action firebase_app_distribution`

[08:54:43]: firebase_cli_path: missing path to firebase cli tool. Please install firebase in $PATH or specify path
```

Ideas?

**Comment by lawicko** [comment]
So it looks like this parameter is not really required, I checked the sources and it just does `which firebase` to determine the path if it's not provided. Google documentation lead me to this problem, so I guess the shame is on them for crating this tutorial: https://firebase.google.com/docs/app-distribution/ios/distribute-fastlane

**Comment by KatieBarnett-Bilue** [comment]
I am having this issue as well.

**Comment by tagboola** [comment]
@lawicko thanks for bringing this to our attention and sorry about that. We plan on updating the docs to clarify the fact that the firebase_cli_path is not required.

@KatieBarnett-Bilue can you send us the output of your command?

**Comment by KatieBarnett-Bilue** [comment]
My output when setting firebase_cli_path:
```
[03:47:33]: Error setting value '/usr/local/bin/firebase' for option 'firebase_cli_path'
--
  | [03:47:33]: You passed invalid parameters to 'firebase_app_distribution'.
  | [03:47:33]: Check out the error below and available options by running `fastlane action firebase_app_distribution`
[03:47:33]: firebase_cli_path: missing path to firebase cli tool. Please install firebase in $PATH or specify path

[03:47:33]: fastlane finished with errors
--
  |  
  | [!] firebase_cli_path: missing path to firebase cli tool. Please install firebase in $PATH or specify path
```

**Comment by tagboola** [comment]
Thanks for sharing your output. Can you verify that the Firebase CLI is in the correct location i.e. `/user/local/bin/firebase`?

**Comment by snatchev** [comment]
This looks like it's resolved with @tagboola's PR. Thanks @tagboola! I'll release a new gem version shortly.

**Comment by DevAbhay23** [comment]
> This looks like it's resolved with @tagboola's PR. Thanks @tagboola! I'll release a new gem version shortly.

Is this issue resolved? I am still facing this issue.

**Comment by sindhu238** [comment]
I am also still facing this issue. If not adding the firebase_cli_path, then i am getting:
firebase_cli_path: missing path to firebase cli tool. Please install firebase in $PATH or specify path. You passed invalid parameters to 'firebase_app_distribution'.

**Comment by Veik404** [comment]
I was facing this issue, its appear that I didn't installed firebase,
then I had to login with 'firebase login'

Hope this can help :)

**Comment by DevAbhay23** [comment]
> I was facing this issue, its appear that I didn't installed firebase,
> then I had to login with 'firebase login'
> 
> Hope this can help :)

I am able to login with firebase login through cmd. But i am still getting:
firebase_cli_path: missing path to firebase cli tool. Please install firebase in $PATH or specify path. You passed invalid parameters to 'firebase_app_distribution'.

**Comment by DevAbhay23** [comment]
> > I was facing this issue, its appear that I didn't installed firebase,
> > then I had to login with 'firebase login'
> > Hope this can help :)
> 
> I am able to login with firebase login through cmd. But i am still getting:
> firebase_cli_path: missing path to firebase cli tool. Please install firebase in $PATH or specify path. You passed invalid parameters to 'firebase_app_distribution'.

Its working now , tried few steps mentioned on stack overflow - https://stackoverflow.com/a/51331108   , and under fastlane file -               
 firebase_app_distribution(
              firebase_cli_path:"C:/Users/xyz/AppData/Roaming/npm/firebase"
        )
